### ISSUE TITLE
NCU/CREDITS window stuck in upper left corner

### ISSUE THREAD

**Issue by amusionist** [dracul89/aou_mod#1]
I love the design but I have one issue: The Credits / NCU window is stuck in the upper left corner and I can not figure out how to move it.

**Comment by dracul89** [comment]
There are several layouts included in this mod I usually like the slim ones. Which one are you using in pedicular? 
![image_2022-11-30_144822396](https://user-images.githubusercontent.com/4844891/204904830-1f8471de-f27c-4c56-af02-6c3e895a2a0f.png)

**Comment by amusionist** [comment]
Ok, I missed that. I was using AOU_CYT ,changed it to one of the others and now ir is like I want.  Thank you for the prompt reply.
